# Generated by Django 5.0.2 on 2025-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pbrand', models.CharField(max_length=20)),
                ('pquantity', models.IntegerField()),
                ('pprice', models.IntegerField()),
            ],
        ),
    ]
