# Generated by Django 5.0.2 on 2025-03-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productt',
            name='pquantity',
        ),
    ]
