# Generated by Django 5.0.2 on 2025-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productt_pquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productt',
            name='pdesc',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productt',
            name='pimg',
            field=models.ImageField(default=False, upload_to='imagessp/'),
        ),
    ]
