# Generated by Django 5.0.2 on 2025-04-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
