# Generated by Django 5.0.2 on 2025-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
