# Generated by Django 5.0.2 on 2025-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
