# Generated by Django 5.0.2 on 2025-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_review_tweet_embed_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=300, verbose_name='http://www.ardentsoftwares.in/index.html')),
            ],
        ),
    ]
