# Generated by Django 5.0.2 on 2025-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='link',
            field=models.URLField(default='http://www.ardentsoftwares.in/index.html', max_length=300),
        ),
    ]
