# Generated by Django 5.0.2 on 2025-05-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryacc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboylog',
            old_name='password',
            new_name='passwordemployee',
        ),
        migrations.RenameField(
            model_name='deliveryboylog',
            old_name='username',
            new_name='usernameemployee',
        ),
    ]
