# Generated by Django 5.0.2 on 2025-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryacc', '0002_rename_password_deliveryboylog_passwordemployee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboylog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
