# Generated by Django 5.0.2 on 2025-05-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryacc', '0003_deliveryboylog_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboylog',
            name='region',
            field=models.CharField(blank=True, choices=[('North Mumbai', 'North Mumbai'), ('South Mumbai', 'South Mumbai')], max_length=100, null=True),
        ),
    ]
